### ISSUE TITLE
アプリアイコンの変更

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#155]
https://pub.dev/packages/flutter_launcher_icons
例：https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example
通常：https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/default
flavor: https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/flavors

flavor : 
flutter_launcher_icons-<flavor>.yaml
```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/demo-icon-dev.png"
```
flutter_launcher_icons/example/flavors/assets/launcher_icon/

を実施後(通常の場合、flavor未確認)
flutter pub get
flutter pub run flutter_launcher_icons:main
